# Generated by Django 4.2.4 on 2023-08-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_categoria_options_alter_produto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="data_criacao",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.PositiveIntegerField(),
        ),
    ]
